### ISSUE TITLE
安装插件joinquery，es无法加载插件导致启动失败

### ISSUE THREAD

**Issue by Zoomtoo** [zhubl/JoinQuery#1]
您好，我有几个问题想问一下
1.使用这个插件有哪些先决条件
2.该插件适配的elastic版本是多少
3.我直接下载zip(因为我的elastic6.5.1安装在windows上)，然后解压至elastic安装目录下的plugins文件夹下，然后重启elastic,就开始报错了，如下所示
F:\elasticsearch-6.5.1\bin>elasticsearch.bat
[2019-01-27T14:20:24,787][INFO ][o.e.e.NodeEnvironment    ] [ClPYzhk] using [1] data paths, mounts [[鏂囦欢 (F:)]], net usable_space [498gb], net total_space [499.9gb], types [NTFS]
[2019-01-27T14:20:24,790][INFO ][o.e.e.NodeEnvironment    ] [ClPYzhk] heap size [494.9mb], compressed ordinary object pointers [true]
[2019-01-27T14:20:24,796][INFO ][o.e.n.Node               ] [ClPYzhk] node name derived from node ID [ClPYzhkXQqi1i1mT3lx58Q]; set [node.name] to override
[2019-01-27T14:20:24,796][INFO ][o.e.n.Node               ] [ClPYzhk] version[6.5.1], pid[57328], build[default/zip/8c58350/2018-11-16T02:22:42.182257Z], OS[Windows 10/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_191/25.191-b12]
[2019-01-27T14:20:24,800][INFO ][o.e.n.Node               ] [ClPYzhk] JVM arguments [-Xms512m, -Xmx512m, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=C:\Users\Administrator\AppData\Local\Temp\elasticsearch, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Delasticsearch, -Des.path.home=F:\elasticsearch-6.5.1, -Des.path.conf=F:\elasticsearch-6.5.1\config, -Des.distribution.flavor=default, -Des.distribution.type=zip]
[2019-01-27T14:20:24,845][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [ClPYzhk] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [JoinQuery]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [JoinQuery]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:394) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:338) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
        ... 6 more
Caused by: java.nio.file.NoSuchFileException: F:\elasticsearch-6.5.1\plugins\JoinQuery\plugin-descriptor.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_191]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_191]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_191]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_191]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:162) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:391) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:379) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:372) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:338) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
        ... 6 more

**Comment by zhubl** [comment]
您好 应该是版本兼容的问题 抱歉一直没维护这个项目
